export type Place = {
  id: number;
  cityId: number;
  districtId: number;
  dongId: number;
  regionName: string;
  title: string;
  desc: string;
  latitude: number;
  longitude: number;
  distance: string;
  rating: number;
  price: string;
  reviewCount: number;
  category: string;
  address: string;
  isWished: boolean;
  imageUrl?: string;
  recommendCount: number;
  visitCount: number;
  commentCount: number;
};
